### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by zupo** [niteoweb/flake8-commitref#1]
Commits should have references to tickets in their text. Create a flake8 plugin that would check that commits contain "refs #" or "Refs #.".

Start by checking only the most recent commit. Then we can come up with a smarter way to select which commits to check (probably something like only checking commits that have not yet been merged into master, if you are currently on a branch).

**Comment by JanLikar** [comment]
I think it would be better to use git commit hooks, specifically the `commit-msg` hook to check this.

**Comment by zupo** [comment]
Not needed any more.
